# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/florian/Documents/ToporobotImporter_QGIS3/ToporobotImporter/toporobotimporter.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToporobotImporter(object):
    def setupUi(self, ToporobotImporter):
        ToporobotImporter.setObjectName("ToporobotImporter")
        ToporobotImporter.resize(585, 547)
        self.buttonBox = QtWidgets.QDialogButtonBox(ToporobotImporter)
        self.buttonBox.setGeometry(QtCore.QRect(10, 510, 561, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gbInput = QtWidgets.QGroupBox(ToporobotImporter)
        self.gbInput.setGeometry(QtCore.QRect(10, 0, 561, 180))
        self.gbInput.setObjectName("gbInput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbInput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.gbInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.leToporobotText = QgsFileWidget(self.gbInput)
        self.leToporobotText.setObjectName("leToporobotText")
        self.horizontalLayout.addWidget(self.leToporobotText)
        self.bBrowseToporobotText = QtWidgets.QToolButton(self.gbInput)
        self.bBrowseToporobotText.setObjectName("bBrowseToporobotText")
        self.horizontalLayout.addWidget(self.bBrowseToporobotText)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gbInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(150, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.leToporobotCoord = QgsFileWidget(self.gbInput)
        self.leToporobotCoord.setObjectName("leToporobotCoord")
        self.horizontalLayout_2.addWidget(self.leToporobotCoord)
        self.bBrowseToporobotCoord = QtWidgets.QToolButton(self.gbInput)
        self.bBrowseToporobotCoord.setObjectName("bBrowseToporobotCoord")
        self.horizontalLayout_2.addWidget(self.bBrowseToporobotCoord)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.gbInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(150, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.leMergeMapping = QgsFileWidget(self.gbInput)
        self.leMergeMapping.setObjectName("leMergeMapping")
        self.horizontalLayout_3.addWidget(self.leMergeMapping)
        self.bBrowseMergeMapping = QtWidgets.QToolButton(self.gbInput)
        self.bBrowseMergeMapping.setObjectName("bBrowseMergeMapping")
        self.horizontalLayout_3.addWidget(self.bBrowseMergeMapping)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.gbInput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(150, 0))
        self.label_5.setBaseSize(QtCore.QSize(150, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.cbDemLayer = QtWidgets.QComboBox(self.gbInput)
        self.cbDemLayer.setObjectName("cbDemLayer")
        self.horizontalLayout_5.addWidget(self.cbDemLayer)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.gbOutput = QtWidgets.QGroupBox(ToporobotImporter)
        self.gbOutput.setGeometry(QtCore.QRect(10, 190, 561, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbOutput.sizePolicy().hasHeightForWidth())
        self.gbOutput.setSizePolicy(sizePolicy)
        self.gbOutput.setObjectName("gbOutput")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbOutput)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.gbOutput)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self._2 = QtWidgets.QHBoxLayout()
        self._2.setObjectName("_2")
        self.label_16 = QtWidgets.QLabel(self.gbOutput)
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/plugins/toporobotimporter/images/schema_points.png"))
        self.label_16.setObjectName("label_16")
        self._2.addWidget(self.label_16)
        self.lbOutPoints = QtWidgets.QLabel(self.gbOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutPoints.sizePolicy().hasHeightForWidth())
        self.lbOutPoints.setSizePolicy(sizePolicy)
        self.lbOutPoints.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutPoints.setObjectName("lbOutPoints")
        self._2.addWidget(self.lbOutPoints)
        self.leOutPoints = QgsFileWidget(self.gbOutput)
        self.leOutPoints.setObjectName("leOutPoints")
        self._2.addWidget(self.leOutPoints)
        self.bBrowseOutPoints = QtWidgets.QToolButton(self.gbOutput)
        self.bBrowseOutPoints.setObjectName("bBrowseOutPoints")
        self._2.addWidget(self.bBrowseOutPoints)
        self.verticalLayout_2.addLayout(self._2)
        self._3 = QtWidgets.QHBoxLayout()
        self._3.setObjectName("_3")
        self.label_17 = QtWidgets.QLabel(self.gbOutput)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/plugins/toporobotimporter/images/schema_lines.png"))
        self.label_17.setObjectName("label_17")
        self._3.addWidget(self.label_17)
        self.lbOutAims = QtWidgets.QLabel(self.gbOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutAims.sizePolicy().hasHeightForWidth())
        self.lbOutAims.setSizePolicy(sizePolicy)
        self.lbOutAims.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutAims.setObjectName("lbOutAims")
        self._3.addWidget(self.lbOutAims)
        self.leOutAims = QgsFileWidget(self.gbOutput)
        self.leOutAims.setObjectName("leOutAims")
        self._3.addWidget(self.leOutAims)
        self.bBrowseOutAims = QtWidgets.QToolButton(self.gbOutput)
        self.bBrowseOutAims.setObjectName("bBrowseOutAims")
        self._3.addWidget(self.bBrowseOutAims)
        self.verticalLayout_2.addLayout(self._3)
        self._4 = QtWidgets.QHBoxLayout()
        self._4.setObjectName("_4")
        self.label_15 = QtWidgets.QLabel(self.gbOutput)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/plugins/toporobotimporter/images/schema_polygons.png"))
        self.label_15.setObjectName("label_15")
        self._4.addWidget(self.label_15)
        self.lbOutAimsSurface = QtWidgets.QLabel(self.gbOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutAimsSurface.sizePolicy().hasHeightForWidth())
        self.lbOutAimsSurface.setSizePolicy(sizePolicy)
        self.lbOutAimsSurface.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutAimsSurface.setObjectName("lbOutAimsSurface")
        self._4.addWidget(self.lbOutAimsSurface)
        self.leOutAimsSurface = QgsFileWidget(self.gbOutput)
        self.leOutAimsSurface.setObjectName("leOutAimsSurface")
        self._4.addWidget(self.leOutAimsSurface)
        self.bBrowseOutAimsSurface = QtWidgets.QToolButton(self.gbOutput)
        self.bBrowseOutAimsSurface.setObjectName("bBrowseOutAimsSurface")
        self._4.addWidget(self.bBrowseOutAimsSurface)
        self.verticalLayout_2.addLayout(self._4)
        self._5 = QtWidgets.QHBoxLayout()
        self._5.setObjectName("_5")
        self.label_13 = QtWidgets.QLabel(self.gbOutput)
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap(":/plugins/toporobotimporter/images/schema_line.png"))
        self.label_13.setObjectName("label_13")
        self._5.addWidget(self.label_13)
        self.lbOutSeries = QtWidgets.QLabel(self.gbOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutSeries.sizePolicy().hasHeightForWidth())
        self.lbOutSeries.setSizePolicy(sizePolicy)
        self.lbOutSeries.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutSeries.setObjectName("lbOutSeries")
        self._5.addWidget(self.lbOutSeries)
        self.leOutSeries = QgsFileWidget(self.gbOutput)
        self.leOutSeries.setEnabled(True)
        self.leOutSeries.setObjectName("leOutSeries")
        self._5.addWidget(self.leOutSeries)
        self.bBrowseOutSeries = QtWidgets.QToolButton(self.gbOutput)
        self.bBrowseOutSeries.setObjectName("bBrowseOutSeries")
        self._5.addWidget(self.bBrowseOutSeries)
        self.verticalLayout_2.addLayout(self._5)
        self._6 = QtWidgets.QHBoxLayout()
        self._6.setObjectName("_6")
        self.label_14 = QtWidgets.QLabel(self.gbOutput)
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap(":/plugins/toporobotimporter/images/schema_polygon.png"))
        self.label_14.setObjectName("label_14")
        self._6.addWidget(self.label_14)
        self.lbOutSeriesBorder = QtWidgets.QLabel(self.gbOutput)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbOutSeriesBorder.sizePolicy().hasHeightForWidth())
        self.lbOutSeriesBorder.setSizePolicy(sizePolicy)
        self.lbOutSeriesBorder.setMinimumSize(QtCore.QSize(100, 0))
        self.lbOutSeriesBorder.setObjectName("lbOutSeriesBorder")
        self._6.addWidget(self.lbOutSeriesBorder)
        self.leOutSeriesBorder = QgsFileWidget(self.gbOutput)
        self.leOutSeriesBorder.setEnabled(True)
        self.leOutSeriesBorder.setObjectName("leOutSeriesBorder")
        self._6.addWidget(self.leOutSeriesBorder)
        self.bBrowseOutSeriesBorder = QtWidgets.QToolButton(self.gbOutput)
        self.bBrowseOutSeriesBorder.setObjectName("bBrowseOutSeriesBorder")
        self._6.addWidget(self.bBrowseOutSeriesBorder)
        self.verticalLayout_2.addLayout(self._6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.gbOutput)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.leSRS = QtWidgets.QLineEdit(self.gbOutput)
        self.leSRS.setObjectName("leSRS")
        self.horizontalLayout_4.addWidget(self.leSRS)
        self.bSRS = QtWidgets.QToolButton(self.gbOutput)
        self.bSRS.setObjectName("bSRS")
        self.horizontalLayout_4.addWidget(self.bSRS)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.gbOutput)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.rbOverride = QtWidgets.QRadioButton(self.gbOutput)
        self.rbOverride.setChecked(True)
        self.rbOverride.setObjectName("rbOverride")
        self.horizontalLayout_6.addWidget(self.rbOverride)
        self.rbAppend = QtWidgets.QRadioButton(self.gbOutput)
        self.rbAppend.setObjectName("rbAppend")
        self.horizontalLayout_6.addWidget(self.rbAppend)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.cbDisplayInQgis = QtWidgets.QCheckBox(self.gbOutput)
        self.cbDisplayInQgis.setChecked(True)
        self.cbDisplayInQgis.setObjectName("cbDisplayInQgis")
        self.verticalLayout_2.addWidget(self.cbDisplayInQgis)

        self.retranslateUi(ToporobotImporter)
        self.buttonBox.accepted.connect(ToporobotImporter.accept)
        self.buttonBox.rejected.connect(ToporobotImporter.reject)
        QtCore.QMetaObject.connectSlotsByName(ToporobotImporter)

    def retranslateUi(self, ToporobotImporter):
        _translate = QtCore.QCoreApplication.translate
        ToporobotImporter.setWindowTitle(_translate("ToporobotImporter", "ToporobotImporter"))
        self.gbInput.setTitle(_translate("ToporobotImporter", "Input data"))
        self.label.setText(_translate("ToporobotImporter", "Toporobot .Text file"))
        self.bBrowseToporobotText.setText(_translate("ToporobotImporter", "Browse"))
        self.label_2.setText(_translate("ToporobotImporter", "Toporobot .Coord file"))
        self.bBrowseToporobotCoord.setText(_translate("ToporobotImporter", "Browse"))
        self.label_4.setText(_translate("ToporobotImporter", "Merge\'s mapping file (optional)"))
        self.bBrowseMergeMapping.setText(_translate("ToporobotImporter", "Browse"))
        self.label_5.setText(_translate("ToporobotImporter", "Layer with Elevation (optional)"))
        self.gbOutput.setTitle(_translate("ToporobotImporter", "Output shapefiles"))
        self.label_9.setText(_translate("ToporobotImporter", "Define the shapefile(s) you want to export (and let the others empty)"))
        self.lbOutPoints.setText(_translate("ToporobotImporter", "Stations as point"))
        self.bBrowseOutPoints.setText(_translate("ToporobotImporter", "Browse"))
        self.lbOutAims.setText(_translate("ToporobotImporter", "Stations as line"))
        self.bBrowseOutAims.setText(_translate("ToporobotImporter", "Browse"))
        self.lbOutAimsSurface.setText(_translate("ToporobotImporter", "Stations as surface"))
        self.bBrowseOutAimsSurface.setText(_translate("ToporobotImporter", "Browse"))
        self.lbOutSeries.setText(_translate("ToporobotImporter", "Series as lines"))
        self.bBrowseOutSeries.setText(_translate("ToporobotImporter", "Browse"))
        self.lbOutSeriesBorder.setText(_translate("ToporobotImporter", "Series as surfaces"))
        self.bBrowseOutSeriesBorder.setText(_translate("ToporobotImporter", "Browse"))
        self.label_6.setText(_translate("ToporobotImporter", "Coordinate reference system (optional)"))
        self.bSRS.setText(_translate("ToporobotImporter", "..."))
        self.label_3.setText(_translate("ToporobotImporter", "Output by"))
        self.rbOverride.setText(_translate("ToporobotImporter", "Overriding"))
        self.rbAppend.setText(_translate("ToporobotImporter", "Appending"))
        self.cbDisplayInQgis.setText(_translate("ToporobotImporter", "Show the created layer(s) in QGIS"))
from qgis.gui import QgsFileWidget
